### ISSUE TITLE
socket:getsockopt(int) does not work while socket:getsockopt(string) does

### ISSUE THREAD

**Issue by miko** [richardhundt/luv#11]
Hello,
after receiving a packet, arguments given as a number fot getsockopt do not work, only strings do. For example:
socket:getsockopt('RCVMORE') - works
socket:getsockopt(luv.zmq.RCVMORE) - does not work

The reason is this code in src/luv_zmq.c in function luv_zmq_socket_getsockopt:

if (lua_isstring(L, 2)) {

which is true for strings as well as numbers. This should be changed to:

if (lua_type(L, 2) == LUA_TSTRING ) {

then it works OK.

**Comment by richardhundt** [comment]
fixed in git HEAD
