### ISSUE TITLE
great work!

### ISSUE THREAD

**Issue by miketang84** [richardhundt/luv#3]
how about the differences between luv and luvit? 

https://github.com/luvit/luvit

**Comment by richardhundt** [comment]
Luvit is more than just libuv bindings. Luvit borrows heavily from node.js's architecture, and they've tweaked a lot of things like lua's module loading. Luvit is an HTTP server too, is statically linked to luajit2, and most importantly, Luvit is callback oriented, with some fiber stuff bolted on the side.

Luv tries to just be libuv bindings, but done in a Lua way. No callbacks. What for? We've got coroutines. Luv is also not ever going to be an HTTP daemon. By all means, build one with it, but I'd rather put http://mongrel2.org in front and let it talk ØMQ to my Luv app.

**Comment by miketang84** [comment]
On Mon, Oct 8, 2012 at 4:25 AM, Richard Hundt notifications@github.comwrote:

> Luvit is more than just libuv bindings. Luvit borrows heavily from
> node.js's architecture, and they've tweaked a lot of things like lua's
> module loading. Luvit is an HTTP server too, is statically linked to
> luajit2, and most importantly, Luvit is callback oriented, with some fiber
> stuff bolted on the side.
> 
> Luv tries to just be libuv bindings, but done in a Lua way. No callbacks.
> What for? We've got coroutines. Luv is also not ever going to be an HTTP
> daemon. By all means, build one with it, but I'd rather put
> http://mongrel2.org in front and let it talk ØMQ to my Luv app.
> 
> I'd like to consider luv as the replacement of mongrel2 ;)
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/richardhundt/luv/issues/3#issuecomment-9212079.

## 

Nothing is impossible.

**Comment by miketang84** [comment]
at least the core of mongrel2.

On Mon, Oct 8, 2012 at 2:55 PM, Tang Daogang daogangtang@gmail.com wrote:

> On Mon, Oct 8, 2012 at 4:25 AM, Richard Hundt notifications@github.comwrote:
> 
> > Luvit is more than just libuv bindings. Luvit borrows heavily from
> > node.js's architecture, and they've tweaked a lot of things like lua's
> > module loading. Luvit is an HTTP server too, is statically linked to
> > luajit2, and most importantly, Luvit is callback oriented, with some fiber
> > stuff bolted on the side.
> > 
> > Luv tries to just be libuv bindings, but done in a Lua way. No callbacks.
> > What for? We've got coroutines. Luv is also not ever going to be an HTTP
> > daemon. By all means, build one with it, but I'd rather put
> > http://mongrel2.org in front and let it talk ØMQ to my Luv app.
> > 
> > I'd like to consider luv as the replacement of mongrel2 ;)
> > 
> >  —
> > Reply to this email directly or view it on GitHubhttps://github.com/richardhundt/luv/issues/3#issuecomment-9212079.
> 
> ## 
> 
> Nothing is impossible.

## 

Nothing is impossible.
