### ISSUE TITLE
no data read out by file:read()

### ISSUE THREAD

**Issue by miketang84** [richardhundt/luv#4]
why file:read() return a number, not the file data?

**Comment by dvv** [comment]
try `print(file:read(n))` -- i believe it returns tuple so `nread, str = file:read()` should work

**Comment by richardhundt** [comment]
On Oct 8, 2012, at 5:32 PM, Vladimir Dronnikov wrote:

> try print(file:read(n)) -- i believe it returns tuple so nread, str = file:read() should work

Correct.

**Comment by miketang84** [comment]
great. I love luv more and more.

On Tue, Oct 9, 2012 at 12:15 AM, Richard Hundt notifications@github.comwrote:

> On Oct 8, 2012, at 5:32 PM, Vladimir Dronnikov wrote:
> 
> > try print(file:read(n)) -- i believe it returns tuple so nread, str =
> > file:read() should work
> 
> Correct.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/richardhundt/luv/issues/4#issuecomment-9231026.

## 

Nothing is impossible.
