### ISSUE TITLE
segment when execute a fs example

### ISSUE THREAD

**Issue by miketang84** [richardhundt/luv#5]
local luv = require 'luv'

local t = luv.fs.stat("/tmp")
for k,v in pairs(t) do
   print(k, "=>", v)
end

**Comment by richardhundt** [comment]
It works for me using git HEAD on both Ubuntu 12.04 and MacOS X. Are you using the latest git?

I'm working furiously on this, so it breaks from time to time. This isn't stable software :)

**Comment by richardhundt** [comment]
I can't repro, but I had this at one stage too and fixed it. Please let me know if the problem persists and I'll investigate.

**Comment by miketang84** [comment]
I update git to today's, segment disappear now. :)

On Tue, Oct 9, 2012 at 3:51 AM, Richard Hundt notifications@github.comwrote:

> I can't repro, but I had this at one stage too and fixed it. Please let me
> know if the problem persists and I'll investigate.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/richardhundt/luv/issues/5#issuecomment-9237948.

## 

Nothing is impossible.
